apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-async-snd
  labels:
    app: ext-async-snd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-async-snd
  template:
    metadata:
      labels:
        app: ext-async-snd
    spec:
      containers:
        - name: ext-async-snd
          image: username/ext-async-snd:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5