---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-async-rcv
  labels:
    app: ext-async-rcv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-async-rcv
  template:
    metadata:
      labels:
        app: ext-async-rcv
    spec:
      containers:
        - name: ext-async-rcv
          image: username/ext-async-rcv:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: intermediary
  labels:
    app: intermediary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intermediary
  template:
    metadata:
      labels:
        app: intermediary
    spec:
      containers:
        - name: intermediary
          image: username/intermediary:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-sync-sndrcv
  labels:
    app: ext-sync-sndrcv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-sync-sndrcv
  template:
    metadata:
      labels:
        app: ext-sync-sndrcv
    spec:
      containers:
        - name: ext-sync-sndrcv
          image: username/ext-sync-sndrcv:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: depositreplyprocess
  labels:
    app: depositreplyprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depositreplyprocess
  template:
    metadata:
      labels:
        app: depositreplyprocess
    spec:
      containers:
        - name: depositreplyprocess
          image: username/depositreplyprocess:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-async-snd
  labels:
    app: ext-async-snd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-async-snd
  template:
    metadata:
      labels:
        app: ext-async-snd
    spec:
      containers:
        - name: ext-async-snd
          image: username/ext-async-snd:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ext-async-rcv
  labels:
    app: ext-async-rcv
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ext-async-rcv


---


apiVersion: v1
kind: Service
metadata:
  name: intermediary
  labels:
    app: intermediary
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: intermediary


---


apiVersion: v1
kind: Service
metadata:
  name: ext-sync-sndrcv
  labels:
    app: ext-sync-sndrcv
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ext-sync-sndrcv


---


apiVersion: v1
kind: Service
metadata:
  name: depositreplyprocess
  labels:
    app: depositreplyprocess
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: depositreplyprocess


---


apiVersion: v1
kind: Service
metadata:
  name: ext-async-snd
  labels:
    app: ext-async-snd
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ext-async-snd

