apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-sync-sndrcv
  labels:
    app: ext-sync-sndrcv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-sync-sndrcv
  template:
    metadata:
      labels:
        app: ext-sync-sndrcv
    spec:
      containers:
        - name: ext-sync-sndrcv
          image: username/ext-sync-sndrcv:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5